---
AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create AWS VPC
Resources:      #Required Field
  CFVPC2:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags:
        - Key: Name
          Value: LearningCF 

