#Template Anatomy
#Format Version
#Description
#Resources
#Parameters 
#Intrinsic Functions
#Metadata- AWS::CloudFormation::Interface 

---
AWSTemplateFormatVersion: "2010-09-09"
Description: Template to create VPC, Subnet, S3 Bucket and EC2 along with parameters section and parameter group
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups:   #List
      - 
        Label: 
          default: "Compute Configurations"
        Parameters: 
          - InstanceTypeParam
          - EC2AMIIDParam
      
      - 
        Label: 
          default: "Storage Configurations"
        Parameters: 
          - S3BucketNameParam

      - 
        Label: 
          default: "Network Configurations"
        Parameters: 
          - VPCCIDRParam
      - 
        Label: 
          default: "Network Configurations"
        Parameters: 
          - SubnetCIDRParam
Parameters:
  EC2AMIIDParam:
    Description: Enter the Image ID
    Type: String
    Default: ami-053a45fff0a704a47
    AllowedValues:
      - ami-053a45fff0a704a47
      - ami-07fa5275316057f54
      - ami-04b4f1a9cf54c11d0
  InstanceTypeParam:
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
  S3BucketNameParam:
    Description: Enter the bucket name # Here we are not providing default value and option as bucket name should be unique so whatever user input will be considered.
    Type: String
  VPCCIDRParam:
    Description: Enter VPC CIDR
    Type: String
    Default: 10.0.0.0/16
    AllowedValues:
      - 10.0.0.0/16
      - 10.0.0.0/8
      - 10.0.0.0/24
  SubnetCIDRParam:
    Description: Enter Subnet CIDR
    Type: String
    Default: 10.0.0.0/24
    AllowedValues:
      - 10.0.0.0/16
      - 10.0.0.0/8
      - 10.0.0.0/24

Resources:      #Required Field
  CFVPC2:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDRParam
      EnableDnsHostnames: True
      EnableDnsSupport: True
      Tags:
        - Key: Name
          Value: LearningCF
  CFSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref CFVPC2
      CidrBlock: !Ref SubnetCIDRParam
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: stack
        Value: dev
  CFS3Bucket: #Logical ID
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketNameParam  #Physical ID
  
  CFEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2AMIIDParam
      InstanceType: !Ref InstanceTypeParam